# this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, restart the server process.
# Site settings. access them via {{ site.title }} etc.

title : computing tools - stat 679 - fall 2016
author :
  name : Cécile Ané
  email : cecile.ane@wisc.edu
  github : cecileane
  twitter : cecileane
  feedburner : nil

production_url : http://cecileane.github.io/computingtools
twitter_username: cecileane
github_username:  cecileane

# Build settings

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
